version: '3.7'

services:
  api:
    volumes:
      - ./api:/api
    env_file:
      - .env
  client:
    volumes:
      - ./client:/client
    env_file:
      - .env
  postgres:
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/initdb.d/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432
    env_file:
      - .env
  nginx:
    env_file:
      - .env
    volumes:
      - ./nginx/ssl:/ssl