version: '3.7'

services:
  server:
    build:
      context: server
    restart: unless-stopped
  postgres:
    build:
      context: postgres
    restart: unless-stopped
  client:
    build:
      context: client
  nginx:
    restart: unless-stopped
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
