version: '3.7'

services:
  server:
    volumes:
      - ./server:/server
    env_file:
      - .env
    ports:
      - 9229:9229
  client:
    volumes:
      - ./client:/client
    env_file:
      - .env
  postgres:
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/initdb.d/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432
    env_file:
      - .env
  nginx:
    env_file:
      - .env
    volumes:
      - ./nginx/ssl:/ssl:rw
      - ./nginx/conf.d/:/conf.d/:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
