version: '3.7'

services:
  mainframe:
    build:
      context: mainframe
    restart: unless-stopped
  postgres:
    build:
      context: postgres
    restart: unless-stopped
  client:
    build:
      context: client
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
  nats:
    build:
      context: nats
  gateway:
    restart: unless-stopped
    build:
      context: gateway
      target: production

